"""Add ticket fields to bookings

Revision ID: 1a2d8bc88af9
Revises: e8511bec278e
Create Date: 2026-07-20 17:40:16.589239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a2d8bc88af9'
down_revision = 'e8511bec278e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('qr_code_data', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ticket_issued_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ticket_checked_in', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('checked_in_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['ticket_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('checked_in_at')
        batch_op.drop_column('ticket_checked_in')
        batch_op.drop_column('ticket_issued_at')
        batch_op.drop_column('qr_code_data')
        batch_op.drop_column('ticket_number')

    # ### end Alembic commands ###
