"""Add payment fields to bookings

Revision ID: f8c3ce3b690f
Revises: 0418a66857d8
Create Date: 2026-07-18 20:22:07.671091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8c3ce3b690f'
down_revision = '0418a66857d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('mpesa_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('paid_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('paid_at')
        batch_op.drop_column('mpesa_code')
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
