from marshmallow import Schema, fields, validate

class EventCreateSchema(Schema):
    title = fields.Str(required=True, validate=validate.Length(min=3, max=200))
    description = fields.Str(required=True, validate=validate.Length(min=10))
    category = fields.Str(required=True, validate=validate.Length(min=2, max=50))
    start_date = fields.DateTime(required=True)
    end_date = fields.DateTime(required=True)
    venue = fields.Str(required=True, validate=validate.Length(min=2, max=200))
    address = fields.Str(required=True, validate=validate.Length(min=5, max=300))
    city = fields.Str(required=True, validate=validate.Length(min=2, max=100))
    latitude = fields.Float()
    longitude = fields.Float()
    capacity = fields.Int(required=True, validate=validate.Range(min=1))
    ticket_price = fields.Float(required=True, validate=validate.Range(min=0))
    image_url = fields.Str()
    status = fields.Str(validate=validate.OneOf(['draft', 'published', 'cancelled', 'completed']))
    is_featured = fields.Bool()

class EventUpdateSchema(Schema):
    title = fields.Str(validate=validate.Length(min=3, max=200))
    description = fields.Str(validate=validate.Length(min=10))
    category = fields.Str(validate=validate.Length(min=2, max=50))
    start_date = fields.DateTime()
    end_date = fields.DateTime()
    venue = fields.Str(validate=validate.Length(min=2, max=200))
    address = fields.Str(validate=validate.Length(min=5, max=300))
    city = fields.Str(validate=validate.Length(min=2, max=100))
    latitude = fields.Float()
    longitude = fields.Float()
    capacity = fields.Int(validate=validate.Range(min=1))
    ticket_price = fields.Float(validate=validate.Range(min=0))
    image_url = fields.Str()
    status = fields.Str(validate=validate.OneOf(['draft', 'published', 'cancelled', 'completed']))
    is_featured = fields.Bool()

class EventResponseSchema(Schema):
    id = fields.Int()
    title = fields.Str()
    description = fields.Str()
    category = fields.Str()
    start_date = fields.DateTime()
    end_date = fields.DateTime()
    venue = fields.Str()
    address = fields.Str()
    city = fields.Str()
    latitude = fields.Float()
    longitude = fields.Float()
    capacity = fields.Int()
    ticket_price = fields.Float()
    image_url = fields.Str()
    status = fields.Str()
    is_featured = fields.Bool()
    created_by = fields.Int()
    created_at = fields.DateTime()
    updated_at = fields.DateTime()
